language: php
sudo: false

php:
    - 7.0
    - 7.1
    - nightly

matrix:
    allow_failures:
        - php: nightly

cache:
    directories:
        - $HOME/.composer/cache

before_script:
    - composer self-update
    - composer install --prefer-dist --ignore-platform-reqs
    - composer dump-autoload -o

script:
    - ./vendor/bin/phpunit --coverage-text
