language: php
sudo: false

php:
    - 7.0
    - 7.1
    - nightly

matrix:
    allow_failures:
        - php: nightly

cache:
    directories:
        - $HOME/.composer/cache

before_install:
    - composer self-update
    - composer dump-autoload -o

install: composer update --prefer-dist

script:
    - ./vendor/bin/phpunit --coverage-text
